
######################## STARTING QUICK SCAN AUTONOMY ########################
 Starting Quickscan CV
Received data from comms simulation: {u'missionInfo': {u'searchArea': {u'topLeft': [36.328375, -121.752615], u'bottomLeft': [35.328375, -121.752615], u'topRight': [36.328375, -120.752615], u'bottomRight': [35.328375, -120.752615]}}, u'type': u'addMission', u'id': 0}
Begin generating waypoints
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Terry H\Documents\GitHub\VTOL\quick_scan_autonomy.py", line 237, in quick_scan_autonomy
    waypoints = generate_waypoints(configs, search_area)
  File "C:\Users\Terry H\Documents\GitHub\VTOL\quick_scan_autonomy.py", line 111, in generate_waypoints
    while tempn <= n2:
NameError: global name 'tempn' is not defined

